#!/bin/bash
#
#SBATCH -o slurm.%N.%j.out
#SBATCH -e slurm.%N.%j.err
#SBATCH --mail-type END
#SBATCH --mail-user b-barckmann@chu-montpellier.fr
#
#
#SBATCH --partition fast
#SBATCH --cpus-per-task 6
#SBATCH --mem 64GB  






module load bedtools/2.30.0

window='5'
genome_chromsize='genome/TriTrypDB-62_TbruceiTREU927_Genome/TriTrypDB-62_TbruceiTREU927_chrom.sizes.txt'
genome='genome/TriTrypDB-62_TbruceiTREU927_Genome/TriTrypDB-62_TbruceiTREU927_Genome.fasta'
pattern='AAAAA'
prefix='Tbruceii_927'


bedtools makewindows \
	-g $genome_chromsize \
	-w $window \
	-s 1  \
	> $prefix\_$window\bps_step1.bed

bedtools nuc \
    -fi $genome \
    -bed Tbruceii_927_5bps_step1.bed \
    -pattern $pattern \
    > NucComp_$prefix\_$window\bps_step1_$pattern\.bed

awk  '{if ($13 > 0) print $1 "\t"  $2 "\t" $3 "\t" $13;}' NucComp_$prefix\_$window\bps_step1_$pattern\.bed > NucComp_$prefix\_$window\bps_step1_$pattern\.bdg  

sed -i -e "1d" NucComp_$prefix\_$window\bps_step1_$pattern\.bdg 

bedtools merge \
    -c 4 -o sum  \
    -i NucComp_$prefix\_$window\bps_step1_$pattern\.bdg \
    > mergedNucComp_$prefix\_$window\bps_step1_$pattern\.bdg 

sort -k1,1 -k2,2n mergedNucComp_$prefix\_$window\bps_step1_$pattern\.bdg  > mergedNucComp_$prefix\_$window\bps_step1_$pattern\_sorted.bdg
